# Generated by Django 6.0.8 on 2026-09-27 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место для совершения привычки", max_length=60, verbose_name="Место"
                    ),
                ),
                ("time", models.TimeField(help_text="Укажите время совершения привычки", verbose_name="Время")),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие совершаемое в качестве привычки",
                        max_length=120,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)],
                        default=1,
                        help_text="Выберите периодичность выполнения привычки",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Укажите время выполнения привычки - от 15 до 120 секунд",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время_на_выполнение(в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте нужно ли опубликовать привычку",
                        verbose_name="Признак_публичности",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли привычка приятной",
                        verbose_name="Признак_приятной_привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после полезной привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите привычку, связанную с этой полезной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habbits.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(auto_now_add=True, verbose_name="Время_завершения")),
                ("is_completed", models.BooleanField(default=True, verbose_name="Выполнена")),
                (
                    "note",
                    models.TextField(blank=True, help_text="Опишите проведение привычки", verbose_name="Заметка"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habbits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "выполнение_привычки",
                "verbose_name_plural": "выполнение_привычек",
                "ordering": ["completed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(condition=models.Q(("duration__lte", 120)), name="duration_max_seconds"),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_enjoyable", True), ("reward__isnull", False), _negated=True),
                name="enjoyable_no_reward",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_enjoyable", True), ("related_habit__isnull", False), _negated=True),
                name="enjoyable_no_related",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("related_habit__isnull", True), ("reward__isnull", True), _connector="OR"),
                name="not_both_related_and_reward",
            ),
        ),
        migrations.AddIndex(
            model_name="habitcompletion",
            index=models.Index(fields=["habit", "completed_at"], name="habbits_hab_habit_i_130081_idx"),
        ),
    ]
