# Generated by Django 6.0.8 on 2026-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "DAILY"),
                    ("two_days", "TWO_DAYS"),
                    ("three_days", "THREE_DAYS"),
                    ("four_days", "FOUR_DAYS"),
                    ("five_days", "FIVE_DAYS"),
                    ("six_days", "SIX_DAYS"),
                    ("seven_days", "SEVEN_DAYS"),
                ],
                default="daily",
                help_text="Выберите периодичность выполнения привычки",
                verbose_name="Периодичность",
            ),
        ),
    ]
