# Generated by Django 6.0.8 on 2026-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0002_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                help_text="Чем пользователь должен себя вознаградить после полезной привычки",
                max_length=200,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
