# Generated by Django 6.0.8 on 2026-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0003_alter_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Чем пользователь должен себя вознаградить после полезной привычки",
                max_length=200,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
