# Generated by Django 6.0.8 on 2026-09-30 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0004_alter_habit_reward"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="habit",
            name="enjoyable_no_reward",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="not_both_related_and_reward",
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_enjoyable", True), models.Q(("reward", ""), _negated=True), _negated=True),
                name="enjoyable_no_reward",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("related_habit__isnull", True), ("reward", ""), _connector="OR"),
                name="not_both_related_and_reward",
            ),
        ),
    ]
